# docker compose version setting
VERSION: '2'

# service setting
services:
  database:
    container_name: fastCampusBoardService # container name setting
    image: mysql:latest # database mysql
    ports:
      - "3336:3306"
    volumes:
      - ./docker/database/:/var/lib/mysql # volume mount setting
    environment:
      MYSQL_ROOT_PASSWORD: won1228
      MYSQL_DATABASE: big_data_study
      MYSQL_USER: study
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul # time zone setting