debug: false # debug mode setting false
management:
  endpoints:
    web:
      exposure:
        include: "*" # manage end point exposure setting
logging:
  level:
    kr.co.won: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  data:
    rest:
      base-path: /api # spring data rest setting path
      detection-strategy: annotated
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password:
#    url: jdbc:mysql://localhost:3306/fastCampusBoardProject
#    username: fastCampus
#    password: 12341234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    #    defer-datasource-initialization: true # test data insert
    properties:
      hibernate: # hibernate setting
        format_sql: true
        default_batch_fetch_size: 100 # change IN query
  #        dialect: org.hibernate.dialect.MySQLInnoDBDialect
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  #      schema-locations: classpath:/../../../sql
  thymeleaf:
    cache: true

---
# sub profile
spring:
  config:
    activate:
      on-profile: testDB
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated
