debug: false # debug mode setting false
management:
  endpoints:
    web:
      exposure:
        include: "*" # manage end point exposure setting
#logging:
#  level:
#    kr.co.won: debug
#    org.springframework.web.servlet: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  sql:
    init:
      mode: ALWAYS
  data:
    rest:
      base-path: /api # spring data rest setting path
      detection-strategy: annotated
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:testDB
    #    username: sa
    #    password:
    url: jdbc:mysql://localhost:3336/fastCampusBoardProject?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLong=999999&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: study
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true # test data insert
    properties:
      hibernate: # hibernate setting
        format_sql: true
        default_batch_fetch_size: 100 # change IN query
#        dialect: org.hibernate.dialect.MySQLInnoDBDialect
  h2:
    console:
      enabled: false
  thymeleaf3:
    decoupled-logic: true
  #        schema-locations: classpath:/../../../sql
  thymeleaf:
    cache: true

#
#---
## sub profile
#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated
